[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
#    Access-Control-Allow-Origin = "https://iframe-vuejs-test.netlify.app https://vibrant-blackwell-b21045.netlify.app http://localhost http://localhost:3000 http://localhost:3001"
     Access-Control-Allow-Origin ="*"
